name: ensemble-doc
channels:
  - licit-lab
  - conda-forge
dependencies:
  - python=3.9
  - pylint
  - black
  - matplotlib=3.4.3
  - numpy=1.21
  - lxml=4.6.4
  - networkx=2.6.3
  - pandas=1.3.4
  - click=8.0.3
  - python-decouple=3.4
  - pytest=6.2.5
  - coverage=6.1.1
  - ipython=7.29.0
  - symuflow=1.1.0
  - pytest=6.2.5
  - coverage=6.1.1
  - pandoc=2.16.1
  - sphinx=4.2.0
  - nbsphinx=0.8.7
  - sphinx-book-theme=0.0.41
  - ipykernel=6.4.2
  - myst-parser=0.15.2
  - pip=21.3.1
