name: ensemble-doc
channels:
  - licit-lab
  - conda-forge
dependencies:
  - python=3.9
  - pylint
  - black
  - matplotlib=3.4.3
  - numpy=1.21
  - lxml=4.6.4
  - networkx=2.6.3
  - pandas=1.3.4
  - click=8.0.3
  - python-decouple=3.4
  - pytest=6.2.5
  - coverage=6.1.1
  - ipython=7.29.0
  - symuflow=1.0.0
  - pytest
  - coverage
  - pandoc
  - sphinx
  - nbsphinx
  - sphinx-book-theme
  - ipykernel
  - myst-parser
  - pip
